#import = ["~/.config/alacritty/themes/tokyonight.yaml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window.padding]
x = 5
y = 5
[window]
# opacity = 0.97
dynamic_padding = true
dynamic_title = false
decorations = "buttonless"
decorations_theme_variant = "None"
startup_mode = "Windowed"


[font]
size = 10

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MonispaceNe Nerd Font"
style = "Medium"

[font.bold]
family = "MonispaceNe Nerd Font"
style = "Bold"

[font.italic]
family = "MonispaceNe Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MonispaceNe Nerd Font"
style = "Bold Italic"

[debug]
render_timer = false

[mouse]
hide_when_typing = true

[shell]
program = "zsh"
#args = ["--login", "-c tmux"]
