[colors.primary]
background = "#16181a"
foreground = "#ffffff"
dim_foreground = "#ffffff"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#16181a"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#16181a"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#16181a"
background = "#ffffff"

[colors.search.focused_match]
foreground = "#16181a"
background = "#5eff6c"

[colors.footer_bar]
foreground = "#16181a"
background = "#ffffff"

[colors.hints.start]
foreground = "#16181a"
background = "#f1ff5e"

[colors.hints.end]
foreground = "#16181a"
background = "#ffffff"

[colors.selection]
text = "#16181a"
background = "#ffffff"

[colors.normal]
black = "#7b8496"
red = "#ff6e5e"
green = "#5eff6c"
yellow = "#f1ff5e"
blue = "#5ea1ff"
magenta = "#ff5ef1"
cyan = "#5ef1ff"
white = "#ffffff"

[colors.bright]
black = "#7b8496"
red = "#ff6e5e"
green = "#5eff6c"
yellow = "#f1ff5e"
blue = "#5ea1ff"
magenta = "#ff5ef1"
cyan = "#5ef1ff"
white = "#ffffff"

[colors.dim]
black = "#7b8496"
red = "#ff6e5e"
green = "#5eff6c"
yellow = "#f1ff5e"
blue = "#5ea1ff"
magenta = "#ff5ef1"
cyan = "#5ef1ff"
white = "#ffffff"

[[colors.indexed_colors]]
index = 16
color = "#ffbd5e"