# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """\
  $directory\
  $cmd_duration\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $line_break\
  $character\
  """

right_format = """\
  $time\
"""

[character]
error_symbol = "✗"

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
show_milliseconds = true

[time]
disabled = false
use_12hr = false

[directory]
truncation_length = 6
truncate_to_repo = true
disabled = false

[hostname]
ssh_only = true
format = "[$hostname]($style) in "
trim_at = "."
disabled = false

[line_break]
disabled = false

[python]
disabled = true

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

