set-option -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'xamut/tmux-spotify'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavour 'macchiato' # or frappe, macchiato, mocha

### Configurazioni per la statusbar
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator "  █"

set -g @catppuccin_window_default_fill "number"

set -g @catppuccin_window_current_fill "number"
#set -g @catppuccin_window_current_text "#{pane_current_path}"

set -g @catppuccin_status_modules_right "application session date_time"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

set -as terminal-features ",*:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"

# Colors
set -g default-terminal "screen-256color"

unbind C-b
set-option -g prefix C-b
bind-key C-b send-prefix

bind V split-window -h
bind B split-window -v

# switch panes using Ctrs-Vimkeys without prefix
unbind l
bind l select-pane -L
unbind h
bind h select-pane -R
unbind k
bind k select-pane -U
unbind j
bind j select-pane -D

####################
##   VIM MOTION   ##
####################
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind -n 'C-\' if-shell "$is_vim" "send-keys 'C-\\'" "select-pane -l"
bind -T copy-mode-vi C-h select-pane -L
bind -T copy-mode-vi C-j select-pane -D
bind -T copy-mode-vi C-k select-pane -U
bind -T copy-mode-vi C-l select-pane -R
bind -T copy-mode-vi 'C-\' select-pane -l

# Auto window renaming OFF
set-option -g allow-rename off

# Vi Mode for copying
setw -g mode-keys vi

unbind '"'
unbind %

set -g mouse on

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded Config"

set-option -g allow-rename off
set-option -g status-position bottom

set -g history-limit 5000                 # boost history

# Window/Pane count index
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Panes/Messages display times
set -g display-panes-time 800
set -g display-time 1000

# Status bar Redraw
set -g status-interval 5

# Activity
set -g monitor-activity off
set -g visual-activity off

# Tmux message prompt
set -g message-style bold

set -g escape-time 10

bind-key -n C-1 select-pane -t 1

bind-key -n C-t neww

run '~/.config/tmux/plugins/tpm/tpm'
