[general]
live_config_reload=true
import=["/Users/antlia/.config/alacritty/zenbones_light.toml"]

[window]
decorations="Buttonless"
dynamic_padding=true
startup_mode="Windowed"
option_as_alt = "OnlyLeft"

[font]
size=18

[font.normal]
family="MonaspiceNE Nerd Font"

[selection]
save_to_clipboard=true

[cursor.style]
shape="Block"
blinking="On"

[mouse]
hide_when_typing=true
