[general]
live_config_reload=true
import=["/Users/antlia/.config/alacritty/catppuccin-latte.toml"]

[window]
decorations="Buttonless"
dynamic_padding=true
startup_mode="Windowed"

[font]
size=12

[font.normal]
family="JetBrainsMono Nerd Font Mono"

[selection]
save_to_clipboard=true

[cursor.style]
shape="Block"
blinking="On"

[mouse]
hide_when_typing=true
